Create pages, routing
pohorielov/feast pull request #1
Opened 2022-10-20 12:39 UTC by pohorielov

2022-10-20 20:06 UTC, Digtyarenk0 requested changes

2022-10-20 20:06 UTC, Digtyarenk0 commented on client/src/pages/Admin.js
> +export default Admin;
Не юзай на компоненты **export default**
Лучше export **const Admin**

2022-10-20 20:06 UTC, Digtyarenk0 commented on client/src/routes.js
> +export const adminRoutes = [
Массив лучше сделать один и на странице самого роута
Я бы держал обьект с путями 
export const mainModuleRoutes = {
  admin: '/admin',
   check: {
      root: '/check',
      watermark: '/check/watermark',
      checkRarible: '/check/rarible',
      checkOpenSea: '/check/opensea',
  },
 }
 А на странице Router 
<img width="710" alt="image" src="https://user-images.githubusercontent.com/66130898/197047198-d4c8074c-0355-45a9-8df1-4c03f2190756.png">

2022-10-21 09:40 UTC, pohorielov commented on client/src/pages/Admin.js
> +export default Admin;
Спасибо, исправил

2022-10-21 09:47 UTC, pohorielov commented on client/src/routes.js
> +export const adminRoutes = [
У меня тут несколько массивов для распределения ролей - к примеру, client имеет доступ к страницам, к которым specialist не может перейти, а не зарегистрированный пользователь - только к главной странице и регистрации. Или это не корректно?

2022-10-26 08:32 UTC, merged